### ISSUE TITLE
Curate github labels

### ISSUE THREAD

**Issue by oswinso** [RoboJackets/igvc-firmware#14]
The github labels for our issues right now are default. We should modify them to be more specific and useful.

AC: Modified github labels.

**Comment by Dallas-D** [comment]
This may be useful https://help.zenhub.com/support/solutions/articles/43000185124-create-the-same-label-set-in-multiple-repos-at-once

**Comment by Dallas-D** [comment]
@oswinso can you review the labels and make sure the labels are what we want?

**Comment by oswinso** [comment]
Looks like this is it. I'm marking this as done.
