### ISSUE TITLE
Group mbed code in a single subdirectory

### ISSUE THREAD

**Issue by Cryptum169** [RoboJackets/igvc-firmware#5]
Can we have the mbed code grouped in a single subfolder so we can start moving firmware for other boards into this repo?

**Comment by oswinso** [comment]
Yeah, sure. I'm thinking of doing something similar to how [robocup-firmware](https://github.com/RoboJackets/robocup-firmware) does it, ie.

- src
    - mbed
    - board1
    - board2

**Comment by Cryptum169** [comment]
Sounds perfect! Just FYI At the moment mbed is the only one that requires a build system (all others runs off Arduino IDE), they only need to exist as single .ino files in separate folders.

**Comment by Cryptum169** [comment]
I just saw the updates in the firmware repo. The majority of other boards is probably not going to be mbeds and we might want to group everything mbed related in its own folder.

**Comment by Cryptum169** [comment]
@oswinso  bump

**Comment by oswinso** [comment]
Alright should be fixed with 8e67039

**Comment by Cryptum169** [comment]
Per #6
